kind = "web"
previewPath = "/"
title = "JobsPicker"
version = "1.0.0"
id = "artifacts/jobspicker"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19676

[services.development]
run = "pnpm --filter @workspace/jobspicker run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/jobspicker", "run", "build" ]
publicDir = "artifacts/jobspicker/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19676"
BASE_PATH = "/"
